### ISSUE TITLE
interested in coming over to WFCD?

### ISSUE THREAD

**Issue by TobiTenno** [WFCD/Warframe.js#1]
we've been thinking about doing something similar to this over in WFCD for a js client, and I'd love to bring this in as the base and enhance from here

**Comment by lucakiebel** [comment]
Haven't seen this earlier, sorry. Sure, would love to work with you guys on a newer version of this.

**Comment by TobiTenno** [comment]
Could you hit me up on discord? `Tobiah#0001`, let's get something in the works!

**Comment by lucakiebel** [comment]
Prime | Luca#1312
