### ISSUE TITLE
Remap?

### ISSUE THREAD

**Issue by TobiTenno** [WFCD/Warframe.js#4]
Looks like current voidTrader is remapped when it's requested.... i think we should either:
- request a remap to this format on worldstate-parser
- keep the same original data mapping as the api

current remapping:
```js
{
  id: trader.id,
  from: new Date(trader.activation),
  until: new Date(trader.expiry),
  name: trader.character,
  relay: trader.location,
  goodies: trader.inventory,
  active: trader.active,
  fromString: `${name} arrives in ${trader.startString}`,
  untilString: `${name} leaves in ${trader.endString}`,
}
```

**Comment by lucakiebel** [comment]
Change it to the mapping from the API is what I'd go with now, I'll have to take a look at current usages though, maybe keep from and until plus activation and expiry

**Comment by TobiTenno** [comment]
Okiedoke. I've started on that in my branch as well as simplifying the calling structure so you don't have quite so much boilerplate
