### ISSUE TITLE
Request-promise depreceated

### ISSUE THREAD

**Issue by AyAyEm** [WFCD/Warframe.js#5]
[Request promise](https://www.npmjs.com/package/request-promise) is deprecated.
Is there any specific need to use it that i'm missing? Or would it be possible to change to [axios](https://github.com/axios/axios) or any other non deprecated library?

**Comment by lucakiebel** [comment]
I'll look into what framework is best later, maybe fetch for TS and then polyfill sth for the browser

**Comment by TobiTenno** [comment]
i'm working on removing this right now for node-fetch, since it uses the same api as `fetch` from the browser, we can do a `window.fetch || require('node-fetch')`
