### ISSUE TITLE
Typescript integration

### ISSUE THREAD

**Issue by AyAyEm** [WFCD/Warframe.js#6]
Is there any plans on typescript integration? Like adding an warframe.d.ts? If not i can start working on it sometime next week.

**Comment by lucakiebel** [comment]
As I wrote in the Discord, I'm just gonna rebuild it in TS. I thought of doing it today, but family calls 🎁

**Comment by TobiTenno** [comment]
i'm working on pulling in warframe-worldstate-parser types so i can auto-generate types for it

**Comment by TobiTenno** [comment]
I kind of hold this opinion:
- allow usage with typescript
- don't lock any usage into either forcing those of use that will probably maintain it (.... me) into using typescript

I'm all for validations that something should work well with typescript, but forcing it isn't great to me?

**Comment by lucakiebel** [comment]
I'm fine with a warframe.d.ts and just leaving it as JS for the app itself
